name: Feature Request
description: Suggest an improvement or new feature for the documentation
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: dropdown
    id: docs-type
    attributes:
      label: "Which documentation should this apply to?"
      options:
        - "Mintlify (docs.maoto.world)"
        - "MkDocs (API Reference - docs.maoto.world/api)"
    validations:
      required: true

  - type: textarea
    id: request
    attributes:
      label: Feature Request
      description: Describe the new feature or improvement.
    validations:
      required: true
