name: Check for PyPI Updates

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6 AM UTC
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Version from PyPI
        id: pypi_version
        run: echo "LATEST_VERSION=$(curl -s https://pypi.org/pypi/maoto-agent/json | jq -r .info.version)" >> $GITHUB_ENV

      - name: Get Last Deployed Version
        id: last_version
        run: echo "LAST_VERSION=$(cat .github/last_deployed_version.txt || echo '0.0.0')" >> $GITHUB_ENV

      - name: Compare Versions
        run: |
          if [ "$LATEST_VERSION" != "$LAST_VERSION" ]; then
            echo "New version detected! Deploying MkDocs..."
            echo "$LATEST_VERSION" > .github/last_deployed_version.txt
            gh workflow run deploy_mkdocs.yml
          else
            echo "No new version detected. Skipping deployment."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
