site_name: Maoto Agent Docs
site_url: https://package.maoto.world/

nav:
  - Home: index.md
  - Installation: installation.md
  - API Reference:
      - Stable: stable/index.md
      - Beta: beta/index.md
      - Python API:
          - Stable: stable/api.md
          - Beta: beta/api.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import os
            - import sys
            - sys.path.append(os.getcwd())
          options:
            show_source: false
  - macros

extra:
  version:
    stable: "latest"
    beta: "dev"
