site_name: MAOTO API Docs
site_url: https://docs.maoto.world/api/
theme:
  name: material

nav:
  - Home: index.md
  - API Reference:
      - Maoto Agent: reference/maoto_agent.md
  - Installation: installation.md
  - Examples: examples.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2
            members_order: source
            docstring_style: numpy
            filters: ["!^_"]
