site_name: Maoto Agent Docs
site_url: https://package.maoto.world/

nav:
  - Home: index.md
  - Package Versions:
      - Stable: stable/api.md
      - Beta: beta/api.md

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: "numpy"
            members: true  # Include only public methods
            filters: ["!^_"]  # Hides private methods (starting with "_")
            inherited_members: true  # Include inherited methods
            merge_init_into_class: true  # Show __init__ details in class doc
  - macros

extra:
  version:
    stable: "latest"
    beta: "dev"
